### ISSUE TITLE
password from

### ISSUE THREAD

**Issue by zzx134196** [mnadjit/notes#1]
May I ask how Michelle's password came from

**Comment by mnadjit** [comment]
When you first get a foothold in the domain on 'WK01' machine, with PowerView you can check which users are ASP-REP-roastable. Alternatively, can use SharpHound and analyze in Bloodhound which also identifies michelle as ASP-REP-Roastable. Then with `impacket-GetNPUsers` we can get the hash and then crack it with hashcat.

**Comment by zzx134196** [comment]
谢谢！




唐宋元明清
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mnadjit/notes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月31日(星期三) 下午3:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mnadjit/notes] password from (Issue #1)





 
When you first get a foothold in the domain on 'WK01' machine, with PowerView you can check which users are ASP-REP-roastable. Alternatively, can use SharpHound and analyze in Bloodhound which also identifies michelle as ASP-REP-Roastable. Then with impacket-GetNPUsers we can get the hash and then crack it with hashcat.
